development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>

development:
  clients:
    default:
      uri: <%= ENV['MONGO_URI'] %>
        
test:
  clients:
    default:
      database: askmbook_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
